---
- name: "Create the vector user"
  ansible.builtin.user:
    create_home: false
    name: "{{ vector_user }}"
    shell: "/bin/false"
    system: true
    state: "present"

- name: "Create a tmp directory"
  ansible.builtin.file:
    path: "{{ tmp_directory_path }}"
    state: "directory"
    mode: '0755'

- name: "Get a vector distrib"
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "{{ tmp_directory_path }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
    mode: '0644'

- name: "Unarchive a vector distrib file"
  ansible.builtin.unarchive:
    src: "{{ tmp_directory_path }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "{{ tmp_directory_path }}"
    remote_src: true

- name: "Create needed vector directory"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    mode: '0755'
    owner: "{{ vector_user }}"
    group: "{{ vector_user }}"
  loop:
    - "/etc/vector"
    - "/var/lib/vector"

- name: "Deploy vector configuration and service"
  ansible.builtin.template:
    src: "{{ item.src_path }}"
    dest: "{{ item.dest_path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - {src_path: "vector.default.j2", dest_path: "/etc/default/vector", owner: "root", group: "root", mode: '0644'}
    - {src_path: "vector.service.j2", dest_path: "/lib/systemd/system/vector.service", owner: "root", group: "root", mode: '0644'}
    - {src_path: "vector.toml.j2", dest_path: "/etc/vector/vector.toml", owner: "{{ vector_user }}", group: "{{ vector_user }}", mode: '0644'}
  notify:
    - "HND_RESTART_VECTOR_SERVICE"

- name: "Copy a vector bin file"
  ansible.builtin.copy:
    src: "{{ tmp_directory_path }}/vector-x86_64-unknown-linux-gnu/bin/vector"
    dest: "/usr/bin/vector"
    owner: "{{ vector_user }}"
    group: "{{ vector_user }}"
    mode: '0755'
    remote_src: true

- name: "Start service vector and enabled"
  ansible.builtin.systemd:
    name: "vector.service"
    state: "started"
    enabled: true
    daemon_reload: true
  

- name: "Remove tmp directory"
  ansible.builtin.file:
    path: "{{ tmp_directory_path }}"
    state: "absent"
  tags:
    - never
    - prod
